[2020/05/30 21:13:11] 127.0.0.1 "/jobs/keyword=C%2B%2B&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:13:11] 127.0.0.1 "/query/keyword=C%2B%2B&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:15:00] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 21:21:24] Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Documents\GitProject\Python-\JobRecruit_website\Log\logging.py", line 21, in wrapped_function
    response = func(*args, **kwargs)
  File "E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py", line 27, in index_handler
    return render(request, "index.html")
  File "D:\Python3.7.5\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python3.7.5\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Python3.7.5\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Python3.7.5\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python3.7.5\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Python3.7.5\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'jobs' not found. 'jobs' is not a valid view function or pattern name.
[2020/05/30 21:22:09] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 21:22:10] 127.0.0.1 "/jobs/keyword=%E5%8C%BA%E5%9D%97%E9%93%BE&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:22:10] 127.0.0.1 "/query/keyword=%E5%8C%BA%E5%9D%97%E9%93%BE&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:29:46] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 21:29:58] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 21:30:01] 127.0.0.1 "/jobs/keyword=C%2B%2B&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:30:01] 127.0.0.1 "/query/keyword=C%2B%2B&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:30:04] 127.0.0.1 "/query/keyword=C%2B%2B&page=3&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:30:07] 127.0.0.1 "/query/keyword=C%2B%2B&page=36&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:30:10] 127.0.0.1 "/jobs/keyword=HTML5&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:30:10] 127.0.0.1 "/query/keyword=HTML5&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:30:12] 127.0.0.1 "/jobs/keyword=HTML&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 21:30:12] 127.0.0.1 "/query/keyword=HTML&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:04:37] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 22:06:07] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 22:27:32] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 22:27:48] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 22:27:49] 127.0.0.1 "/jobs/keyword=%E5%8C%BA%E5%9D%97%E9%93%BE&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:27:49] 127.0.0.1 "/query/keyword=%E5%8C%BA%E5%9D%97%E9%93%BE&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:27:50] 127.0.0.1 "/query/keyword=%E5%8C%BA%E5%9D%97%E9%93%BE&page=3&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:27:52] 127.0.0.1 "/query/keyword=%E5%8C%BA%E5%9D%97%E9%93%BE&page=84&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:27:53] 127.0.0.1 "/jobs/keyword=&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:27:53] 127.0.0.1 "/query/keyword=&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:27:54] 127.0.0.1 "/jobs/keyword=&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:27:54] 127.0.0.1 "/query/keyword=&page=1&num=15 HTTP/1.1" GET 200 
[2020/05/30 22:37:59] Not Found: /user/register
[2020/05/30 22:39:39] Not Found: /user/register
[2020/05/30 22:39:44] Not Found: /user/register
[2020/05/30 22:42:32] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 22:42:43] Internal Server Error: /register
Traceback (most recent call last):
  File "D:\Python3.7.5\lib\site-packages\django\urls\base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'goods'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py", line 139, in post
    return register_handle(request)
  File "E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py", line 131, in register_handle
    return redirect(reverse('goods:index'))
  File "D:\Python3.7.5\lib\site-packages\django\urls\base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'goods' is not a registered namespace
[2020/05/30 22:44:13] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 22:44:30] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 22:44:53] Not Found: /user/active/eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5MDg0OTc2MiwiZXhwIjoxNTkwODUzMzYyfQ.eyJjb25maXJtIjoxfQ.gLR8aDjpkKdLp76tI69lVtn8GBnU8AK1ZSD5sNyeSXYFWBnL0D9ePVAk5kDh-NSeGiqLF3ezwQIaa1WMuUDP6A
[2020/05/30 22:47:56] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 22:48:10] E:\Documents\GitProject\Python-\JobRecruit_website\celery_tasks\tasks.py changed, reloading.
[2020/05/30 22:48:14] Not Found: /active/eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5MDg0OTc2MiwiZXhwIjoxNTkwODUzMzYyfQ.eyJjb25maXJtIjoxfQ.gLR8aDjpkKdLp76tI69lVtn8GBnU8AK1ZSD5sNyeSXYFWBnL0D9ePVAk5kDh-NSeGiqLF3ezwQIaa1WMuUDP6A
[2020/05/30 22:48:55] E:\Documents\GitProject\Python-\JobRecruit_website\user\urls.py changed, reloading.
[2020/05/30 22:49:12] E:\Documents\GitProject\Python-\JobRecruit_website\user\urls.py changed, reloading.
[2020/05/30 22:49:49] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 22:57:54] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 22:58:28] Internal Server Error: /login
Traceback (most recent call last):
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py", line 197, in post
    next_url = request.GET.get('next', reverse('user:index'))  # 获取不到next时，转到首页
  File "D:\Python3.7.5\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Python3.7.5\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
[2020/05/30 22:59:12] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 22:59:14] Forbidden (CSRF token missing or incorrect.): /login
[2020/05/30 22:59:19] Forbidden (CSRF token missing or incorrect.): /login
[2020/05/30 22:59:21] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 22:59:29] Internal Server Error: /login
Traceback (most recent call last):
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py", line 197, in post
    next_url = request.GET.get('next', reverse('user'))  # 获取不到next时，转到首页
  File "D:\Python3.7.5\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Python3.7.5\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
[2020/05/30 22:59:35] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 22:59:37] Forbidden (CSRF token missing or incorrect.): /login
[2020/05/30 22:59:39] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 22:59:45] Internal Server Error: /login
Traceback (most recent call last):
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py", line 197, in post
    next_url = request.GET.get('next', reverse(''))  # 获取不到next时，转到首页
  File "D:\Python3.7.5\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Python3.7.5\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
[2020/05/30 23:07:48] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 23:07:51] Forbidden (CSRF token missing or incorrect.): /login
[2020/05/30 23:07:54] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:08:03] Internal Server Error: /login
Traceback (most recent call last):
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python3.7.5\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py", line 201, in post
    response = redirect(next_url)
  File "D:\Python3.7.5\lib\site-packages\django\shortcuts.py", line 58, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "D:\Python3.7.5\lib\site-packages\django\shortcuts.py", line 148, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\Python3.7.5\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Python3.7.5\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
[2020/05/30 23:08:37] E:\Documents\GitProject\Python-\JobRecruit_website\user\urls.py changed, reloading.
[2020/05/30 23:08:44] E:\Documents\GitProject\Python-\JobRecruit_website\user\views.py changed, reloading.
[2020/05/30 23:09:15] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:09:22] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:15:16] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:15:28] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:15:33] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:15:56] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:16:12] Not Found: /user/active/eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5MDg1MTc1NSwiZXhwIjoxNTkwODU1MzU1fQ.eyJjb25maXJtIjoyfQ.xBkcYZLXE9QnirhjsFx6X-Nmyp60U7B1tfPOYqck4idwyJeUDv8qSBLZirG6pcurBuTMy-gHdTDPREMYxFHg5g
[2020/05/30 23:16:44] E:\Documents\GitProject\Python-\JobRecruit_website\celery_tasks\tasks.py changed, reloading.
[2020/05/30 23:18:11] Not Found: /user/active/eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5MDg1MTc1NSwiZXhwIjoxNTkwODU1MzU1fQ.eyJjb25maXJtIjoyfQ.xBkcYZLXE9QnirhjsFx6X-Nmyp60U7B1tfPOYqck4idwyJeUDv8qSBLZirG6pcurBuTMy-gHdTDPREMYxFHg5g
[2020/05/30 23:18:24] Not Found: /user/active/eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5MDg1MTc1NSwiZXhwIjoxNTkwODU1MzU1fQ.eyJjb25maXJtIjoyfQ.xBkcYZLXE9QnirhjsFx6X-Nmyp60U7B1tfPOYqck4idwyJeUDv8qSBLZirG6pcurBuTMy-gHdTDPREMYxFHg5g
[2020/05/30 23:41:37] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:41:40] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:41:54] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:43:09] E:\Documents\GitProject\Python-\JobRecruit_website\manage.py changed, reloading.
[2020/05/30 23:44:12] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/30 23:53:45] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/31 00:20:31] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/31 00:20:38] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/31 00:37:44] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/31 00:38:01] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/31 00:38:35] 127.0.0.1 "// HTTP/1.1" GET 200 
[2020/05/31 00:39:02] E:\Documents\GitProject\Python-\JobRecruit_website\celery_tasks\tasks.py changed, reloading.
